version: '3'
services:
    #Mysql database
    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password # use the legacy authentication plugin
        container_name: mysql-container
        restart: always
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: .t€St.
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: test
        cap_add:
            - SYS_NICE  # Avoid Warning: mysql-container | mbind: Operation not permitted
        ports:
            - 33061:3306
        volumes:
            - ".data:/var/lib/mysql"
        networks:
            - app-network-test

    #Nest enviroment
    node:
        build:
            context: .
            dockerfile: Dockerfile
        image: node:latest-alpine
        container_name: node-container
        restart: always
        tty: true
        environment:
            NODE_ENV: development
        ports:
            - "4000:3000"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        networks:
            - app-network-test

#Docker Networks
networks:
  app-network-test:
    driver: bridge
